// IP_Tests_esRAM_AVMM_0.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module IP_Tests_esRAM_AVMM_0 (
		input  wire [19:0] av_address,       //             av.address
		input  wire        av_write,         //               .write
		input  wire [31:0] av_writedata,     //               .writedata
		input  wire        av_read,          //               .read
		output wire [31:0] av_readdata,      //               .readdata
		output wire        av_waitrequest,   //               .waitrequest
		output wire        reset_n,          //          reset.reset_n
		output wire        esram_clk_locked, // esram_locked_1.esram_clk_locked
		output wire        esram_clk,        //      esram_clk.clk
		input  wire        refclk            //        ref_clk.clk
	);

	esRAM_device esram_avmm_0 (
		.av_address       (av_address),       //   input,  width = 20,             av.address
		.av_write         (av_write),         //   input,   width = 1,               .write
		.av_writedata     (av_writedata),     //   input,  width = 32,               .writedata
		.av_read          (av_read),          //   input,   width = 1,               .read
		.av_readdata      (av_readdata),      //  output,  width = 32,               .readdata
		.av_waitrequest   (av_waitrequest),   //  output,   width = 1,               .waitrequest
		.reset_n          (reset_n),          //  output,   width = 1,          reset.reset_n
		.esram_clk_locked (esram_clk_locked), //  output,   width = 1, esram_locked_1.esram_clk_locked
		.esram_clk        (esram_clk),        //  output,   width = 1,      esram_clk.clk
		.refclk           (refclk)            //   input,   width = 1,        ref_clk.clk
	);

endmodule
