// qsys_top_spi_slave_to_avmm_master_bridge.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module qsys_top_spi_slave_to_avmm_master_bridge (
		input  wire        clk,                                                                    //           clk.clk
		input  wire        reset_n,                                                                //       reset_n.reset_n
		input  wire        mosi_to_the_spislave_inst_for_spichain,                                 //      export_0.mosi_to_the_spislave_inst_for_spichain
		input  wire        nss_to_the_spislave_inst_for_spichain,                                  //              .nss_to_the_spislave_inst_for_spichain
		input  wire        sclk_to_the_spislave_inst_for_spichain,                                 //              .sclk_to_the_spislave_inst_for_spichain
		inout  wire        miso_to_and_from_the_spislave_inst_for_spichain,                        //              .miso_to_and_from_the_spislave_inst_for_spichain
		output wire [31:0] address_from_the_altera_avalon_packets_to_master_inst_for_spichain,     // avalon_master.address
		output wire [3:0]  byteenable_from_the_altera_avalon_packets_to_master_inst_for_spichain,  //              .byteenable
		output wire        read_from_the_altera_avalon_packets_to_master_inst_for_spichain,        //              .read
		input  wire [31:0] readdata_to_the_altera_avalon_packets_to_master_inst_for_spichain,      //              .readdata
		input  wire        readdatavalid_to_the_altera_avalon_packets_to_master_inst_for_spichain, //              .readdatavalid
		input  wire        waitrequest_to_the_altera_avalon_packets_to_master_inst_for_spichain,   //              .waitrequest
		output wire        write_from_the_altera_avalon_packets_to_master_inst_for_spichain,       //              .write
		output wire [31:0] writedata_from_the_altera_avalon_packets_to_master_inst_for_spichain    //              .writedata
	);

	SPISlaveToAvalonMasterBridge qsys_top_spi_slave_to_avmm_master_bridge (
		.clk                                                                    (clk),                                                                    //   input,   width = 1,           clk.clk
		.reset_n                                                                (reset_n),                                                                //   input,   width = 1,       reset_n.reset_n
		.mosi_to_the_spislave_inst_for_spichain                                 (mosi_to_the_spislave_inst_for_spichain),                                 //   input,   width = 1,      export_0.export
		.nss_to_the_spislave_inst_for_spichain                                  (nss_to_the_spislave_inst_for_spichain),                                  //   input,   width = 1,              .export
		.sclk_to_the_spislave_inst_for_spichain                                 (sclk_to_the_spislave_inst_for_spichain),                                 //   input,   width = 1,              .export
		.miso_to_and_from_the_spislave_inst_for_spichain                        (miso_to_and_from_the_spislave_inst_for_spichain),                        //   inout,   width = 1,              .export
		.address_from_the_altera_avalon_packets_to_master_inst_for_spichain     (address_from_the_altera_avalon_packets_to_master_inst_for_spichain),     //  output,  width = 32, avalon_master.address
		.byteenable_from_the_altera_avalon_packets_to_master_inst_for_spichain  (byteenable_from_the_altera_avalon_packets_to_master_inst_for_spichain),  //  output,   width = 4,              .byteenable
		.read_from_the_altera_avalon_packets_to_master_inst_for_spichain        (read_from_the_altera_avalon_packets_to_master_inst_for_spichain),        //  output,   width = 1,              .read
		.readdata_to_the_altera_avalon_packets_to_master_inst_for_spichain      (readdata_to_the_altera_avalon_packets_to_master_inst_for_spichain),      //   input,  width = 32,              .readdata
		.readdatavalid_to_the_altera_avalon_packets_to_master_inst_for_spichain (readdatavalid_to_the_altera_avalon_packets_to_master_inst_for_spichain), //   input,   width = 1,              .readdatavalid
		.waitrequest_to_the_altera_avalon_packets_to_master_inst_for_spichain   (waitrequest_to_the_altera_avalon_packets_to_master_inst_for_spichain),   //   input,   width = 1,              .waitrequest
		.write_from_the_altera_avalon_packets_to_master_inst_for_spichain       (write_from_the_altera_avalon_packets_to_master_inst_for_spichain),       //  output,   width = 1,              .write
		.writedata_from_the_altera_avalon_packets_to_master_inst_for_spichain   (writedata_from_the_altera_avalon_packets_to_master_inst_for_spichain)    //  output,  width = 32,              .writedata
	);

endmodule
