// altera_ep_g3x16_avst512_io_pll_s10.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module altera_ep_g3x16_avst512_io_pll_s10 (
		input  wire  rst,        //      reset.reset
		input  wire  refclk,     //     refclk.clk
		output wire  locked,     //     locked.export
		input  wire  permit_cal, // permit_cal.export
		output wire  outclk_0    //    outclk0.clk
	);

	qsys_top_avmm_bridge_512_0_altera_iopll_1931_p2t7wuy altera_ep_g3x16_avst512_io_pll_s10 (
		.rst        (rst),        //   input,  width = 1,      reset.reset
		.refclk     (refclk),     //   input,  width = 1,     refclk.clk
		.locked     (locked),     //  output,  width = 1,     locked.export
		.permit_cal (permit_cal), //   input,  width = 1, permit_cal.export
		.outclk_0   (outclk_0)    //  output,  width = 1,    outclk0.clk
	);

endmodule
