// qsfp_pio_0.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module qsfp_pio_0 (
		input  wire        clk,        //                 clk.clk
		input  wire        reset_n,    //               reset.reset_n
		input  wire [2:0]  address,    //                  s1.address
		input  wire        write_n,    //                    .write_n
		input  wire [31:0] writedata,  //                    .writedata
		input  wire        chipselect, //                    .chipselect
		output wire [31:0] readdata,   //                    .readdata
		inout  wire [3:0]  bidir_port  // external_connection.export
	);

	qsfp_pio_0_altera_avalon_pio_1910_cybtl6a qsfp_pio_0 (
		.clk        (clk),        //   input,   width = 1,                 clk.clk
		.reset_n    (reset_n),    //   input,   width = 1,               reset.reset_n
		.address    (address),    //   input,   width = 3,                  s1.address
		.write_n    (write_n),    //   input,   width = 1,                    .write_n
		.writedata  (writedata),  //   input,  width = 32,                    .writedata
		.chipselect (chipselect), //   input,   width = 1,                    .chipselect
		.readdata   (readdata),   //  output,  width = 32,                    .readdata
		.bidir_port (bidir_port)  //   inout,   width = 4, external_connection.export
	);

endmodule
