// system_manager_flash_memory_buffer.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module system_manager_flash_memory_buffer (
		input  wire [8:0]  address,     //     s1.address
		input  wire        clken,       //       .clken
		input  wire        chipselect,  //       .chipselect
		input  wire        write,       //       .write
		output wire [15:0] readdata,    //       .readdata
		input  wire [15:0] writedata,   //       .writedata
		input  wire [1:0]  byteenable,  //       .byteenable
		input  wire [8:0]  address2,    //     s2.address
		input  wire        chipselect2, //       .chipselect
		input  wire        clken2,      //       .clken
		input  wire        write2,      //       .write
		output wire [15:0] readdata2,   //       .readdata
		input  wire [15:0] writedata2,  //       .writedata
		input  wire [1:0]  byteenable2, //       .byteenable
		input  wire        clk,         //   clk1.clk
		input  wire        reset,       // reset1.reset
		input  wire        reset_req    //       .reset_req
	);

	system_manager_flash_memory_buffer_altera_avalon_onchip_memory2_1920_6adre4i flash_memory_buffer (
		.address     (address),     //   input,   width = 9,     s1.address
		.clken       (clken),       //   input,   width = 1,       .clken
		.chipselect  (chipselect),  //   input,   width = 1,       .chipselect
		.write       (write),       //   input,   width = 1,       .write
		.readdata    (readdata),    //  output,  width = 16,       .readdata
		.writedata   (writedata),   //   input,  width = 16,       .writedata
		.byteenable  (byteenable),  //   input,   width = 2,       .byteenable
		.address2    (address2),    //   input,   width = 9,     s2.address
		.chipselect2 (chipselect2), //   input,   width = 1,       .chipselect
		.clken2      (clken2),      //   input,   width = 1,       .clken
		.write2      (write2),      //   input,   width = 1,       .write
		.readdata2   (readdata2),   //  output,  width = 16,       .readdata
		.writedata2  (writedata2),  //   input,  width = 16,       .writedata
		.byteenable2 (byteenable2), //   input,   width = 2,       .byteenable
		.clk         (clk),         //   input,   width = 1,   clk1.clk
		.reset       (reset),       //   input,   width = 1, reset1.reset
		.reset_req   (reset_req),   //   input,   width = 1,       .reset_req
		.freeze      (1'b0)         // (terminated),                     
	);

endmodule
