# TCL File Generated by Component Editor 20.3
# Wed Apr 16 22:37:47 EDT 2025
# DO NOT MODIFY


# 
# avmm_to_esram "avmm_to_esram" v1.0
#  2025.04.16.22:37:47
# 
# 

# 
# request TCL package from ACDS 20.3
# 
package require -exact qsys 20.3


# 
# module avmm_to_esram
# 
set_module_property DESCRIPTION ""
set_module_property NAME avmm_to_esram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avmm_to_esram
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL av_esram
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file av_esram.v VERILOG PATH ../rtl/av_esram.v TOP_LEVEL_FILE
add_fileset_file bretime.vhd VHDL PATH ../rtl/bretime.vhd


# 
# parameters
# 
add_parameter c_ADDR_BITS INTEGER 16
set_parameter_property c_ADDR_BITS DEFAULT_VALUE 16
set_parameter_property c_ADDR_BITS DISPLAY_NAME c_ADDR_BITS
set_parameter_property c_ADDR_BITS UNITS None
set_parameter_property c_ADDR_BITS AFFECTS_GENERATION false
set_parameter_property c_ADDR_BITS HDL_PARAMETER true
add_parameter c_WORD_SIZE INTEGER 32
set_parameter_property c_WORD_SIZE DEFAULT_VALUE 32
set_parameter_property c_WORD_SIZE DISPLAY_NAME c_WORD_SIZE
set_parameter_property c_WORD_SIZE UNITS None
set_parameter_property c_WORD_SIZE AFFECTS_GENERATION false
set_parameter_property c_WORD_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point av
# 
add_interface av avalon end
set_interface_property av addressGroup 0
set_interface_property av addressUnits WORDS
set_interface_property av associatedClock esram_clk
set_interface_property av associatedReset esram_rst
set_interface_property av bitsPerSymbol 8
set_interface_property av bridgedAddressOffset ""
set_interface_property av bridgesToMaster ""
set_interface_property av burstOnBurstBoundariesOnly false
set_interface_property av burstcountUnits WORDS
set_interface_property av explicitAddressSpan 0
set_interface_property av holdTime 0
set_interface_property av linewrapBursts false
set_interface_property av maximumPendingReadTransactions 0
set_interface_property av maximumPendingWriteTransactions 0
set_interface_property av minimumResponseLatency 1
set_interface_property av readLatency 0
set_interface_property av readWaitTime 1
set_interface_property av setupTime 0
set_interface_property av timingUnits Cycles
set_interface_property av transparentBridge false
set_interface_property av waitrequestAllowance 0
set_interface_property av writeWaitTime 0
set_interface_property av ENABLED true
set_interface_property av EXPORT_OF ""
set_interface_property av PORT_NAME_MAP ""
set_interface_property av CMSIS_SVD_VARIABLES ""
set_interface_property av SVD_ADDRESS_GROUP ""
set_interface_property av IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port av av_address address Input "((c_ADDR_BITS - 1)) - (0) + 1"
add_interface_port av av_read read Input 1
add_interface_port av av_waitrequest waitrequest Output 1
add_interface_port av av_write write Input 1
add_interface_port av av_readdata readdata Output "((c_WORD_SIZE - 1)) - (0) + 1"
add_interface_port av av_writedata writedata Input "((c_WORD_SIZE - 1)) - (0) + 1"
set_interface_assignment av embeddedsw.configuration.isFlash 0
set_interface_assignment av embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ram_input
# 
add_interface ram_input conduit end
set_interface_property ram_input associatedClock ""
set_interface_property ram_input associatedReset ""
set_interface_property ram_input ENABLED true
set_interface_property ram_input EXPORT_OF ""
set_interface_property ram_input PORT_NAME_MAP ""
set_interface_property ram_input CMSIS_SVD_VARIABLES ""
set_interface_property ram_input SVD_ADDRESS_GROUP ""
set_interface_property ram_input IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ram_input data s2c0_da_0 Output "((c_WORD_SIZE - 1)) - (0) + 1"
add_interface_port ram_input rdaddress s2c0_adrb_0 Output "((c_ADDR_BITS - 1)) - (0) + 1"
add_interface_port ram_input rden_n s2c0_meb_n_0 Output 1
add_interface_port ram_input sd_n s2c0_sd_n_0 Output 1
add_interface_port ram_input wraddress s2c0_adra_0 Output "((c_ADDR_BITS - 1)) - (0) + 1"
add_interface_port ram_input wren_n s2c0_mea_n_0 Output 1
add_interface_port ram_input refclk_out clock Output 1


# 
# connection point ram_output
# 
add_interface ram_output conduit end
set_interface_property ram_output associatedClock ""
set_interface_property ram_output associatedReset ""
set_interface_property ram_output ENABLED true
set_interface_property ram_output EXPORT_OF ""
set_interface_property ram_output PORT_NAME_MAP ""
set_interface_property ram_output CMSIS_SVD_VARIABLES ""
set_interface_property ram_output SVD_ADDRESS_GROUP ""
set_interface_property ram_output IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ram_output q s2c0_qb_0 Input "((c_WORD_SIZE - 1)) - (0) + 1"
add_interface_port ram_output esram_clk_i esram2f_clk Input 1
add_interface_port ram_output iopll_lock2core iopll_lock2core Input 1


# 
# connection point iopll_lock
# 
add_interface iopll_lock conduit end
set_interface_property iopll_lock associatedClock ""
set_interface_property iopll_lock associatedReset ""
set_interface_property iopll_lock ENABLED true
set_interface_property iopll_lock EXPORT_OF ""
set_interface_property iopll_lock PORT_NAME_MAP ""
set_interface_property iopll_lock CMSIS_SVD_VARIABLES ""
set_interface_property iopll_lock SVD_ADDRESS_GROUP ""
set_interface_property iopll_lock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port iopll_lock iopll_lock writeresponsevalid_n Output 1


# 
# connection point refclk
# 
add_interface refclk clock end
set_interface_property refclk ENABLED true
set_interface_property refclk EXPORT_OF ""
set_interface_property refclk PORT_NAME_MAP ""
set_interface_property refclk CMSIS_SVD_VARIABLES ""
set_interface_property refclk SVD_ADDRESS_GROUP ""
set_interface_property refclk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port refclk refclk clk Input 1


# 
# connection point esram_clk
# 
add_interface esram_clk clock start
set_interface_property esram_clk associatedDirectClock ""
set_interface_property esram_clk ENABLED true
set_interface_property esram_clk EXPORT_OF ""
set_interface_property esram_clk PORT_NAME_MAP ""
set_interface_property esram_clk CMSIS_SVD_VARIABLES ""
set_interface_property esram_clk SVD_ADDRESS_GROUP ""
set_interface_property esram_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port esram_clk esram_clk clk Output 1


# 
# connection point esram_rst
# 
add_interface esram_rst reset start
set_interface_property esram_rst associatedClock refclk
set_interface_property esram_rst associatedDirectReset ""
set_interface_property esram_rst associatedResetSinks ""
set_interface_property esram_rst synchronousEdges DEASSERT
set_interface_property esram_rst ENABLED true
set_interface_property esram_rst EXPORT_OF ""
set_interface_property esram_rst PORT_NAME_MAP ""
set_interface_property esram_rst CMSIS_SVD_VARIABLES ""
set_interface_property esram_rst SVD_ADDRESS_GROUP ""
set_interface_property esram_rst IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port esram_rst esram_rst reset Output 1

