// s10_chip_id.v

// Generated using ACDS version 19.4 64

`timescale 1 ps / 1 ps
module s10_chip_id (
		input  wire        clk,        //    clk.clk
		input  wire        reset,      //  reset.reset
		output wire        data_valid, // output.valid
		output wire [63:0] chip_id,    //       .data
		input  wire        readid      // readid.readid
	);

	s10_chip_id_altera_s10_chip_id_1911_iexnkcy s10_chip_id_0 (
		.clk        (clk),        //   input,   width = 1,    clk.clk
		.reset      (reset),      //   input,   width = 1,  reset.reset
		.data_valid (data_valid), //  output,   width = 1, output.valid
		.chip_id    (chip_id),    //  output,  width = 64,       .data
		.readid     (readid)      //   input,   width = 1, readid.readid
	);

endmodule
