// PCIe_to_BMC_IRQ_Generator_0.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module PCIe_to_BMC_IRQ_Generator_0 (
		input  wire [1:0]  address,    //    avalon_slave_0.address
		input  wire        chipselect, //                  .chipselect
		input  wire        write_n,    //                  .write_n
		input  wire [31:0] writedata,  //                  .writedata
		output wire [31:0] readdata,   //                  .readdata
		input  wire        clk,        //             clock.clk
		input  wire        reset_n,    //             reset.reset_n
		input  wire [1:0]  irq_in,     // Ext_irq_interface.irq_in
		output wire        irq         //  interrupt_sender.irq
	);

	irq_generator pcie_to_bmc_irq_generator_0 (
		.address    (address),    //   input,   width = 2,    avalon_slave_0.address
		.chipselect (chipselect), //   input,   width = 1,                  .chipselect
		.write_n    (write_n),    //   input,   width = 1,                  .write_n
		.writedata  (writedata),  //   input,  width = 32,                  .writedata
		.readdata   (readdata),   //  output,  width = 32,                  .readdata
		.clk        (clk),        //   input,   width = 1,             clock.clk
		.reset_n    (reset_n),    //   input,   width = 1,             reset.reset_n
		.irq_in     (irq_in),     //   input,   width = 2, Ext_irq_interface.irq_in
		.irq        (irq)         //  output,   width = 1,  interrupt_sender.irq
	);

endmodule
