// esram_7.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module esram_7 (
		output wire [31:0] c7_q_0,          // ram_output.s2c7_qb_0
		output wire        esram2f_clk,     //           .esram2f_clk
		output wire        iopll_lock2core, //           .iopll_lock2core
		input  wire [31:0] c7_data_0,       //  ram_input.s2c7_da_0
		input  wire [10:0] c7_rdaddress_0,  //           .s2c7_adrb_0
		input  wire        c7_rden_n_0,     //           .s2c7_meb_n_0
		input  wire        c7_sd_n_0,       //           .s2c7_sd_n_0
		input  wire [10:0] c7_wraddress_0,  //           .s2c7_adra_0
		input  wire        c7_wren_n_0,     //           .s2c7_mea_n_0
		input  wire        refclk           //           .clock
	);

	esram_7_esram_1915_m2z7ffi #(
		.c0_address_width  (11),
		.c1_address_width  (11),
		.c2_address_width  (11),
		.c3_address_width  (11),
		.c4_address_width  (11),
		.c5_address_width  (11),
		.c6_address_width  (11),
		.c7_address_width  (11),
		.c0_data_width     (72),
		.c1_data_width     (72),
		.c2_data_width     (72),
		.c3_data_width     (72),
		.c4_data_width     (72),
		.c5_data_width     (72),
		.c6_data_width     (72),
		.c7_data_width     (32),
		.c0_disable        ("TRUE"),
		.c1_disable        ("TRUE"),
		.c2_disable        ("TRUE"),
		.c3_disable        ("TRUE"),
		.c4_disable        ("TRUE"),
		.c5_disable        ("TRUE"),
		.c6_disable        ("TRUE"),
		.c7_disable        ("FALSE"),
		.c0_bank_enable    ("C0_EN_0BANK"),
		.c1_bank_enable    ("C1_EN_0BANK"),
		.c2_bank_enable    ("C2_EN_0BANK"),
		.c3_bank_enable    ("C3_EN_0BANK"),
		.c4_bank_enable    ("C4_EN_0BANK"),
		.c5_bank_enable    ("C5_EN_0BANK"),
		.c6_bank_enable    ("C6_EN_0BANK"),
		.c7_bank_enable    ("C7_EN_1BANK"),
		.c0_ecc_enable     ("FALSE"),
		.c1_ecc_enable     ("FALSE"),
		.c2_ecc_enable     ("FALSE"),
		.c3_ecc_enable     ("FALSE"),
		.c4_ecc_enable     ("FALSE"),
		.c5_ecc_enable     ("FALSE"),
		.c6_ecc_enable     ("FALSE"),
		.c7_ecc_enable     ("FALSE"),
		.c0_ecc_byp_enable ("FALSE"),
		.c1_ecc_byp_enable ("FALSE"),
		.c2_ecc_byp_enable ("FALSE"),
		.c3_ecc_byp_enable ("FALSE"),
		.c4_ecc_byp_enable ("FALSE"),
		.c5_ecc_byp_enable ("FALSE"),
		.c6_ecc_byp_enable ("FALSE"),
		.c7_ecc_byp_enable ("FALSE"),
		.c0_wr_fwd_enable  ("FALSE"),
		.c1_wr_fwd_enable  ("FALSE"),
		.c2_wr_fwd_enable  ("FALSE"),
		.c3_wr_fwd_enable  ("FALSE"),
		.c4_wr_fwd_enable  ("FALSE"),
		.c5_wr_fwd_enable  ("FALSE"),
		.c6_wr_fwd_enable  ("FALSE"),
		.c7_wr_fwd_enable  ("FALSE"),
		.c0_lpmode_enable  ("FALSE"),
		.c1_lpmode_enable  ("FALSE"),
		.c2_lpmode_enable  ("FALSE"),
		.c3_lpmode_enable  ("FALSE"),
		.c4_lpmode_enable  ("FALSE"),
		.c5_lpmode_enable  ("FALSE"),
		.c6_lpmode_enable  ("FALSE"),
		.c7_lpmode_enable  ("FALSE"),
		.clock_rate        ("FULLRATE")
	) esram_0 (
		.c7_q_0          (c7_q_0),          //  output,  width = 32, ram_output.s2c7_qb_0
		.esram2f_clk     (esram2f_clk),     //  output,   width = 1,           .esram2f_clk
		.iopll_lock2core (iopll_lock2core), //  output,   width = 1,           .iopll_lock2core
		.c7_data_0       (c7_data_0),       //   input,  width = 32,  ram_input.s2c7_da_0
		.c7_rdaddress_0  (c7_rdaddress_0),  //   input,  width = 11,           .s2c7_adrb_0
		.c7_rden_n_0     (c7_rden_n_0),     //   input,   width = 1,           .s2c7_meb_n_0
		.c7_sd_n_0       (c7_sd_n_0),       //   input,   width = 1,           .s2c7_sd_n_0
		.c7_wraddress_0  (c7_wraddress_0),  //   input,  width = 11,           .s2c7_adra_0
		.c7_wren_n_0     (c7_wren_n_0),     //   input,   width = 1,           .s2c7_mea_n_0
		.refclk          (refclk)           //   input,   width = 1,           .clock
	);

endmodule
