-- esram.vhd

-- Generated using ACDS version 19.1 240

library IEEE;
library esram_191;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity esram is
  port (
    c0_q_0          : out std_logic_vector(31 downto 0);  -- ram_output.s2c0_qb_0
    esram2f_clk     : out std_logic;    --           .esram2f_clk
    iopll_lock2core : out std_logic;    --           .iopll_lock2core
    c0_data_0       : in  std_logic_vector(31 downto 0) := (others => '0');  --  ram_input.s2c0_da_0
    c0_rdaddress_0  : in  std_logic_vector(10 downto 0) := (others => '0');  --           .s2c0_adrb_0
    c0_rden_n_0     : in  std_logic                     := '0';  --           .s2c0_meb_n_0
    c0_sd_n_0       : in  std_logic                     := '0';  --           .s2c0_sd_n_0
    c0_wraddress_0  : in  std_logic_vector(10 downto 0) := (others => '0');  --           .s2c0_adra_0
    c0_wren_n_0     : in  std_logic                     := '0';  --           .s2c0_mea_n_0
    refclk          : in  std_logic                     := '0'  --           .clock
    );
end entity esram;

architecture rtl of esram is
  component esram_esram_191_bykom6q_cmp is
                                          generic (
                                            c0_address_width  :     integer                                       := 17;
                                            c1_address_width  :     integer                                       := 17;
                                            c2_address_width  :     integer                                       := 17;
                                            c3_address_width  :     integer                                       := 17;
                                            c4_address_width  :     integer                                       := 17;
                                            c5_address_width  :     integer                                       := 17;
                                            c6_address_width  :     integer                                       := 17;
                                            c7_address_width  :     integer                                       := 17;
                                            c0_data_width     :     integer                                       := 72;
                                            c1_data_width     :     integer                                       := 72;
                                            c2_data_width     :     integer                                       := 72;
                                            c3_data_width     :     integer                                       := 72;
                                            c4_data_width     :     integer                                       := 72;
                                            c5_data_width     :     integer                                       := 72;
                                            c6_data_width     :     integer                                       := 72;
                                            c7_data_width     :     integer                                       := 72;
                                            c0_disable        :     string                                        := "FALSE";
                                            c1_disable        :     string                                        := "TRUE";
                                            c2_disable        :     string                                        := "TRUE";
                                            c3_disable        :     string                                        := "TRUE";
                                            c4_disable        :     string                                        := "TRUE";
                                            c5_disable        :     string                                        := "TRUE";
                                            c6_disable        :     string                                        := "TRUE";
                                            c7_disable        :     string                                        := "TRUE";
                                            c0_bank_enable    :     string                                        := "C0_EN_0BANK";
                                            c1_bank_enable    :     string                                        := "C1_EN_0BANK";
                                            c2_bank_enable    :     string                                        := "C2_EN_0BANK";
                                            c3_bank_enable    :     string                                        := "C3_EN_0BANK";
                                            c4_bank_enable    :     string                                        := "C4_EN_0BANK";
                                            c5_bank_enable    :     string                                        := "C5_EN_0BANK";
                                            c6_bank_enable    :     string                                        := "C6_EN_0BANK";
                                            c7_bank_enable    :     string                                        := "C7_EN_0BANK";
                                            c0_ecc_enable     :     string                                        := "FALSE";
                                            c1_ecc_enable     :     string                                        := "FALSE";
                                            c2_ecc_enable     :     string                                        := "FALSE";
                                            c3_ecc_enable     :     string                                        := "FALSE";
                                            c4_ecc_enable     :     string                                        := "FALSE";
                                            c5_ecc_enable     :     string                                        := "FALSE";
                                            c6_ecc_enable     :     string                                        := "FALSE";
                                            c7_ecc_enable     :     string                                        := "FALSE";
                                            c0_ecc_byp_enable :     string                                        := "FALSE";
                                            c1_ecc_byp_enable :     string                                        := "FALSE";
                                            c2_ecc_byp_enable :     string                                        := "FALSE";
                                            c3_ecc_byp_enable :     string                                        := "FALSE";
                                            c4_ecc_byp_enable :     string                                        := "FALSE";
                                            c5_ecc_byp_enable :     string                                        := "FALSE";
                                            c6_ecc_byp_enable :     string                                        := "FALSE";
                                            c7_ecc_byp_enable :     string                                        := "FALSE";
                                            c0_wr_fwd_enable  :     string                                        := "FALSE";
                                            c1_wr_fwd_enable  :     string                                        := "FALSE";
                                            c2_wr_fwd_enable  :     string                                        := "FALSE";
                                            c3_wr_fwd_enable  :     string                                        := "FALSE";
                                            c4_wr_fwd_enable  :     string                                        := "FALSE";
                                            c5_wr_fwd_enable  :     string                                        := "FALSE";
                                            c6_wr_fwd_enable  :     string                                        := "FALSE";
                                            c7_wr_fwd_enable  :     string                                        := "FALSE";
                                            c0_lpmode_enable  :     string                                        := "FALSE";
                                            c1_lpmode_enable  :     string                                        := "FALSE";
                                            c2_lpmode_enable  :     string                                        := "FALSE";
                                            c3_lpmode_enable  :     string                                        := "FALSE";
                                            c4_lpmode_enable  :     string                                        := "FALSE";
                                            c5_lpmode_enable  :     string                                        := "FALSE";
                                            c6_lpmode_enable  :     string                                        := "FALSE";
                                            c7_lpmode_enable  :     string                                        := "FALSE";
                                            clock_rate        :     string                                        := "FULLRATE"
                                            );
                                        port (
                                          c0_q_0              : out std_logic_vector(31 downto 0);  -- s2c0_qb_0
                                          esram2f_clk         : out std_logic;  -- esram2f_clk
                                          iopll_lock2core     : out std_logic;  -- iopll_lock2core
                                          c0_data_0           : in  std_logic_vector(31 downto 0)                 := (others => 'X');  -- s2c0_da_0
                                          c0_rdaddress_0      : in  std_logic_vector(c0_address_width-1 downto 0) := (others => 'X');  -- s2c0_adrb_0
                                          c0_rden_n_0         : in  std_logic                                     := 'X';  -- s2c0_meb_n_0
                                          c0_sd_n_0           : in  std_logic                                     := 'X';  -- s2c0_sd_n_0
                                          c0_wraddress_0      : in  std_logic_vector(c0_address_width-1 downto 0) := (others => 'X');  -- s2c0_adra_0
                                          c0_wren_n_0         : in  std_logic                                     := 'X';  -- s2c0_mea_n_0
                                          refclk          : in  std_logic                                     := 'X'              -- clock
                                          );
  end component esram_esram_191_bykom6q_cmp;

  for esram_0 : esram_esram_191_bykom6q_cmp
    use entity esram_191.esram_esram_191_bykom6q;
begin

  esram_0 : component esram_esram_191_bykom6q_cmp
    generic map (
      c0_address_width  => 11,
      c1_address_width  => 11,
      c2_address_width  => 11,
      c3_address_width  => 11,
      c4_address_width  => 11,
      c5_address_width  => 11,
      c6_address_width  => 11,
      c7_address_width  => 11,
      c0_data_width     => 32,
      c1_data_width     => 72,
      c2_data_width     => 72,
      c3_data_width     => 72,
      c4_data_width     => 72,
      c5_data_width     => 72,
      c6_data_width     => 72,
      c7_data_width     => 72,
      c0_disable        => "FALSE",
      c1_disable        => "TRUE",
      c2_disable        => "TRUE",
      c3_disable        => "TRUE",
      c4_disable        => "TRUE",
      c5_disable        => "TRUE",
      c6_disable        => "TRUE",
      c7_disable        => "TRUE",
      c0_bank_enable    => "C0_EN_1BANK",
      c1_bank_enable    => "C1_EN_0BANK",
      c2_bank_enable    => "C2_EN_0BANK",
      c3_bank_enable    => "C3_EN_0BANK",
      c4_bank_enable    => "C4_EN_0BANK",
      c5_bank_enable    => "C5_EN_0BANK",
      c6_bank_enable    => "C6_EN_0BANK",
      c7_bank_enable    => "C7_EN_0BANK",
      c0_ecc_enable     => "FALSE",
      c1_ecc_enable     => "FALSE",
      c2_ecc_enable     => "FALSE",
      c3_ecc_enable     => "FALSE",
      c4_ecc_enable     => "FALSE",
      c5_ecc_enable     => "FALSE",
      c6_ecc_enable     => "FALSE",
      c7_ecc_enable     => "FALSE",
      c0_ecc_byp_enable => "FALSE",
      c1_ecc_byp_enable => "FALSE",
      c2_ecc_byp_enable => "FALSE",
      c3_ecc_byp_enable => "FALSE",
      c4_ecc_byp_enable => "FALSE",
      c5_ecc_byp_enable => "FALSE",
      c6_ecc_byp_enable => "FALSE",
      c7_ecc_byp_enable => "FALSE",
      c0_wr_fwd_enable  => "FALSE",
      c1_wr_fwd_enable  => "FALSE",
      c2_wr_fwd_enable  => "FALSE",
      c3_wr_fwd_enable  => "FALSE",
      c4_wr_fwd_enable  => "FALSE",
      c5_wr_fwd_enable  => "FALSE",
      c6_wr_fwd_enable  => "FALSE",
      c7_wr_fwd_enable  => "FALSE",
      c0_lpmode_enable  => "FALSE",
      c1_lpmode_enable  => "FALSE",
      c2_lpmode_enable  => "FALSE",
      c3_lpmode_enable  => "FALSE",
      c4_lpmode_enable  => "FALSE",
      c5_lpmode_enable  => "FALSE",
      c6_lpmode_enable  => "FALSE",
      c7_lpmode_enable  => "FALSE",
      clock_rate        => "FULLRATE"
      )
    port map (
      c0_q_0          => c0_q_0,          -- ram_output.s2c0_qb_0
      esram2f_clk     => esram2f_clk,     --           .esram2f_clk
      iopll_lock2core => iopll_lock2core, --           .iopll_lock2core
      c0_data_0       => c0_data_0,       --  ram_input.s2c0_da_0
      c0_rdaddress_0  => c0_rdaddress_0,  --           .s2c0_adrb_0
      c0_rden_n_0     => c0_rden_n_0,     --           .s2c0_meb_n_0
      c0_sd_n_0       => c0_sd_n_0,       --           .s2c0_sd_n_0
      c0_wraddress_0  => c0_wraddress_0,  --           .s2c0_adra_0
      c0_wren_n_0     => c0_wren_n_0,     --           .s2c0_mea_n_0
      refclk          => refclk           --           .clock
      );

end architecture rtl; -- of esram
